name: 01 - Local
values:
  - key: URL_BASE_TRUCO_HTTP
    value: 'localhost:8080/api'
  - key: matchId
    value: ''
  - key: accessTokenPlayerOne
    value: ''
  - key: refreshTokenPlayerOne
    value: ''
  - key: accessTokenPlayerOneExpiresAt
    value: ''
  - key: refreshTokenPlayerOneExpiresAt
    value: ''
  - key: accessTokenPlayerTwo
    value: ''
  - key: refreshTokenPlayerTwo
    value: ''
  - key: accessTokenPlayerTwoExpiresAt
    value: ''
  - key: refreshTokenPlayerTwoExpiresAt
    value: ''
  - key: accessTokenPlayerThree
    value: ''
  - key: accessTokenPlayerThreeExpiresAt
    value: ''
  - key: accessTokenPlayerFour
    value: ''
  - key: accessTokenPlayerFourExpiresAt
    value: ''
  - key: accessTokenPlayerFive
    value: ''
  - key: accessTokenPlayerFiveExpiresAt
    value: ''
  - key: accessTokenPlayerSix
    value: ''
  - key: accessTokenPlayerSixExpiresAt
    value: ''
  - key: joinCode
    value: ''
  - key: leagueId
    value: ''
  - key: cupId
    value: ''
  - key: parentType
    value: ''
  - key: parentId
    value: ''
  - key: invitationId
    value: ''
  - key: targetId
    value: ''
