package com.villo.truco.profile.domain.model;

public enum AchievementCode {
  WIN_ENVIDO_2_2_MANO_ZERO,
  WIN_FALTA_ENVIDO_2_2_MANO_33,
  WIN_BY_QUIERO_Y_ME_VOY_AL_MAZO,
  WIN_BY_CUTTING_ROUND_WITH_ANCHO_DE_ESPADA,
  FOLD_ON_FIRST_HAND,
  WIN_RETRUCO_FROM_0_0_TO_3,
  WIN_REAL_OR_FALTA_FROM_0_0,
  WIN_TRUCO_AGAINST_BUSTED_OPPONENT_WITHOUT_ACCEPT_AND_FOLD,
  WIN_AT_2_2_WITHOUT_CALLS_IN_ROUND,
  WIN_AFTER_LOSING_ACCEPTED_VALE_CUATRO_BY_BUST
}
